/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db;


import ch.martinelli.demo.jooq.db.tables.Fruits;
import ch.martinelli.demo.jooq.db.tables.StoreFruitPrices;
import ch.martinelli.demo.jooq.db.tables.Stores;
import ch.martinelli.demo.jooq.db.tables.records.FruitsRecord;
import ch.martinelli.demo.jooq.db.tables.records.StoreFruitPricesRecord;
import ch.martinelli.demo.jooq.db.tables.records.StoresRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FruitsRecord> FRUITS_NAME_KEY = Internal.createUniqueKey(Fruits.FRUITS, DSL.name("fruits_name_key"), new TableField[] { Fruits.FRUITS.NAME }, true);
    public static final UniqueKey<FruitsRecord> FRUITS_PKEY = Internal.createUniqueKey(Fruits.FRUITS, DSL.name("fruits_pkey"), new TableField[] { Fruits.FRUITS.ID }, true);
    public static final UniqueKey<StoreFruitPricesRecord> STORE_FRUIT_PRICES_PKEY = Internal.createUniqueKey(StoreFruitPrices.STORE_FRUIT_PRICES, DSL.name("store_fruit_prices_pkey"), new TableField[] { StoreFruitPrices.STORE_FRUIT_PRICES.FRUIT_ID, StoreFruitPrices.STORE_FRUIT_PRICES.STORE_ID }, true);
    public static final UniqueKey<StoresRecord> STORES_NAME_KEY = Internal.createUniqueKey(Stores.STORES, DSL.name("stores_name_key"), new TableField[] { Stores.STORES.NAME }, true);
    public static final UniqueKey<StoresRecord> STORES_PKEY = Internal.createUniqueKey(Stores.STORES, DSL.name("stores_pkey"), new TableField[] { Stores.STORES.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<StoreFruitPricesRecord, FruitsRecord> STORE_FRUIT_PRICES__FRUIT_ID_FK = Internal.createForeignKey(StoreFruitPrices.STORE_FRUIT_PRICES, DSL.name("fruit_id_fk"), new TableField[] { StoreFruitPrices.STORE_FRUIT_PRICES.FRUIT_ID }, Keys.FRUITS_PKEY, new TableField[] { Fruits.FRUITS.ID }, true);
    public static final ForeignKey<StoreFruitPricesRecord, StoresRecord> STORE_FRUIT_PRICES__STORE_ID_FK = Internal.createForeignKey(StoreFruitPrices.STORE_FRUIT_PRICES, DSL.name("store_id_fk"), new TableField[] { StoreFruitPrices.STORE_FRUIT_PRICES.STORE_ID }, Keys.STORES_PKEY, new TableField[] { Stores.STORES.ID }, true);
}
