/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db;


import ch.martinelli.demo.jooq.db.tables.Fruits;
import ch.martinelli.demo.jooq.db.tables.StoreFruitPrices;
import ch.martinelli.demo.jooq.db.tables.Stores;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.fruits</code>.
     */
    public final Fruits FRUITS = Fruits.FRUITS;

    /**
     * The table <code>public.store_fruit_prices</code>.
     */
    public final StoreFruitPrices STORE_FRUIT_PRICES = StoreFruitPrices.STORE_FRUIT_PRICES;

    /**
     * The table <code>public.stores</code>.
     */
    public final Stores STORES = Stores.STORES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.FRUITS_SEQ,
            Sequences.STORES_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Fruits.FRUITS,
            StoreFruitPrices.STORE_FRUIT_PRICES,
            Stores.STORES
        );
    }
}
