/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.fruits_seq</code>
     */
    public static final Sequence<Long> FRUITS_SEQ = Internal.createSequence("fruits_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 11, null, null, null, false, null);

    /**
     * The sequence <code>public.stores_seq</code>
     */
    public static final Sequence<Long> STORES_SEQ = Internal.createSequence("stores_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 9, null, null, null, false, null);
}
