/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db;


import ch.martinelli.demo.jooq.db.tables.Fruits;
import ch.martinelli.demo.jooq.db.tables.StoreFruitPrices;
import ch.martinelli.demo.jooq.db.tables.Stores;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.fruits</code>.
     */
    public static final Fruits FRUITS = Fruits.FRUITS;

    /**
     * The table <code>public.store_fruit_prices</code>.
     */
    public static final StoreFruitPrices STORE_FRUIT_PRICES = StoreFruitPrices.STORE_FRUIT_PRICES;

    /**
     * The table <code>public.stores</code>.
     */
    public static final Stores STORES = Stores.STORES;
}
