/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db.tables;


import ch.martinelli.demo.jooq.db.Keys;
import ch.martinelli.demo.jooq.db.Public;
import ch.martinelli.demo.jooq.db.tables.StoreFruitPrices.StoreFruitPricesPath;
import ch.martinelli.demo.jooq.db.tables.Stores.StoresPath;
import ch.martinelli.demo.jooq.db.tables.records.FruitsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fruits extends TableImpl<FruitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fruits</code>
     */
    public static final Fruits FRUITS = new Fruits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FruitsRecord> getRecordType() {
        return FruitsRecord.class;
    }

    /**
     * The column <code>public.fruits.id</code>.
     */
    public final TableField<FruitsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fruits.description</code>.
     */
    public final TableField<FruitsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.fruits.name</code>.
     */
    public final TableField<FruitsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Fruits(Name alias, Table<FruitsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Fruits(Name alias, Table<FruitsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.fruits</code> table reference
     */
    public Fruits(String alias) {
        this(DSL.name(alias), FRUITS);
    }

    /**
     * Create an aliased <code>public.fruits</code> table reference
     */
    public Fruits(Name alias) {
        this(alias, FRUITS);
    }

    /**
     * Create a <code>public.fruits</code> table reference
     */
    public Fruits() {
        this(DSL.name("fruits"), null);
    }

    public <O extends Record> Fruits(Table<O> path, ForeignKey<O, FruitsRecord> childPath, InverseForeignKey<O, FruitsRecord> parentPath) {
        super(path, childPath, parentPath, FRUITS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FruitsPath extends Fruits implements Path<FruitsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FruitsPath(Table<O> path, ForeignKey<O, FruitsRecord> childPath, InverseForeignKey<O, FruitsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FruitsPath(Name alias, Table<FruitsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FruitsPath as(String alias) {
            return new FruitsPath(DSL.name(alias), this);
        }

        @Override
        public FruitsPath as(Name alias) {
            return new FruitsPath(alias, this);
        }

        @Override
        public FruitsPath as(Table<?> alias) {
            return new FruitsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FruitsRecord> getPrimaryKey() {
        return Keys.FRUITS_PKEY;
    }

    @Override
    public List<UniqueKey<FruitsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FRUITS_NAME_KEY);
    }

    private transient StoreFruitPricesPath _storeFruitPrices;

    /**
     * Get the implicit to-many join path to the
     * <code>public.store_fruit_prices</code> table
     */
    public StoreFruitPricesPath storeFruitPrices() {
        if (_storeFruitPrices == null)
            _storeFruitPrices = new StoreFruitPricesPath(this, null, Keys.STORE_FRUIT_PRICES__FRUIT_ID_FK.getInverseKey());

        return _storeFruitPrices;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.stores</code>
     * table
     */
    public StoresPath stores() {
        return storeFruitPrices().stores();
    }

    @Override
    public Fruits as(String alias) {
        return new Fruits(DSL.name(alias), this);
    }

    @Override
    public Fruits as(Name alias) {
        return new Fruits(alias, this);
    }

    @Override
    public Fruits as(Table<?> alias) {
        return new Fruits(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fruits rename(String name) {
        return new Fruits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fruits rename(Name name) {
        return new Fruits(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fruits rename(Table<?> name) {
        return new Fruits(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fruits where(Condition condition) {
        return new Fruits(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fruits where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fruits where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fruits where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fruits where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fruits where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fruits where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fruits where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fruits whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fruits whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
