/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db.tables;


import ch.martinelli.demo.jooq.db.Keys;
import ch.martinelli.demo.jooq.db.Public;
import ch.martinelli.demo.jooq.db.tables.Fruits.FruitsPath;
import ch.martinelli.demo.jooq.db.tables.Stores.StoresPath;
import ch.martinelli.demo.jooq.db.tables.records.StoreFruitPricesRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoreFruitPrices extends TableImpl<StoreFruitPricesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.store_fruit_prices</code>
     */
    public static final StoreFruitPrices STORE_FRUIT_PRICES = new StoreFruitPrices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoreFruitPricesRecord> getRecordType() {
        return StoreFruitPricesRecord.class;
    }

    /**
     * The column <code>public.store_fruit_prices.price</code>.
     */
    public final TableField<StoreFruitPricesRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC(12, 2).nullable(false), this, "");

    /**
     * The column <code>public.store_fruit_prices.fruit_id</code>.
     */
    public final TableField<StoreFruitPricesRecord, Long> FRUIT_ID = createField(DSL.name("fruit_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.store_fruit_prices.store_id</code>.
     */
    public final TableField<StoreFruitPricesRecord, Long> STORE_ID = createField(DSL.name("store_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private StoreFruitPrices(Name alias, Table<StoreFruitPricesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StoreFruitPrices(Name alias, Table<StoreFruitPricesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.store_fruit_prices</code> table reference
     */
    public StoreFruitPrices(String alias) {
        this(DSL.name(alias), STORE_FRUIT_PRICES);
    }

    /**
     * Create an aliased <code>public.store_fruit_prices</code> table reference
     */
    public StoreFruitPrices(Name alias) {
        this(alias, STORE_FRUIT_PRICES);
    }

    /**
     * Create a <code>public.store_fruit_prices</code> table reference
     */
    public StoreFruitPrices() {
        this(DSL.name("store_fruit_prices"), null);
    }

    public <O extends Record> StoreFruitPrices(Table<O> path, ForeignKey<O, StoreFruitPricesRecord> childPath, InverseForeignKey<O, StoreFruitPricesRecord> parentPath) {
        super(path, childPath, parentPath, STORE_FRUIT_PRICES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StoreFruitPricesPath extends StoreFruitPrices implements Path<StoreFruitPricesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StoreFruitPricesPath(Table<O> path, ForeignKey<O, StoreFruitPricesRecord> childPath, InverseForeignKey<O, StoreFruitPricesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StoreFruitPricesPath(Name alias, Table<StoreFruitPricesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StoreFruitPricesPath as(String alias) {
            return new StoreFruitPricesPath(DSL.name(alias), this);
        }

        @Override
        public StoreFruitPricesPath as(Name alias) {
            return new StoreFruitPricesPath(alias, this);
        }

        @Override
        public StoreFruitPricesPath as(Table<?> alias) {
            return new StoreFruitPricesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StoreFruitPricesRecord> getPrimaryKey() {
        return Keys.STORE_FRUIT_PRICES_PKEY;
    }

    @Override
    public List<ForeignKey<StoreFruitPricesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STORE_FRUIT_PRICES__FRUIT_ID_FK, Keys.STORE_FRUIT_PRICES__STORE_ID_FK);
    }

    private transient FruitsPath _fruits;

    /**
     * Get the implicit join path to the <code>public.fruits</code> table.
     */
    public FruitsPath fruits() {
        if (_fruits == null)
            _fruits = new FruitsPath(this, Keys.STORE_FRUIT_PRICES__FRUIT_ID_FK, null);

        return _fruits;
    }

    private transient StoresPath _stores;

    /**
     * Get the implicit join path to the <code>public.stores</code> table.
     */
    public StoresPath stores() {
        if (_stores == null)
            _stores = new StoresPath(this, Keys.STORE_FRUIT_PRICES__STORE_ID_FK, null);

        return _stores;
    }

    @Override
    public StoreFruitPrices as(String alias) {
        return new StoreFruitPrices(DSL.name(alias), this);
    }

    @Override
    public StoreFruitPrices as(Name alias) {
        return new StoreFruitPrices(alias, this);
    }

    @Override
    public StoreFruitPrices as(Table<?> alias) {
        return new StoreFruitPrices(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreFruitPrices rename(String name) {
        return new StoreFruitPrices(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreFruitPrices rename(Name name) {
        return new StoreFruitPrices(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StoreFruitPrices rename(Table<?> name) {
        return new StoreFruitPrices(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreFruitPrices where(Condition condition) {
        return new StoreFruitPrices(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreFruitPrices where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreFruitPrices where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreFruitPrices where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreFruitPrices where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreFruitPrices where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreFruitPrices where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StoreFruitPrices where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreFruitPrices whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StoreFruitPrices whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
