/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db.tables;


import ch.martinelli.demo.jooq.db.Keys;
import ch.martinelli.demo.jooq.db.Public;
import ch.martinelli.demo.jooq.db.tables.Fruits.FruitsPath;
import ch.martinelli.demo.jooq.db.tables.StoreFruitPrices.StoreFruitPricesPath;
import ch.martinelli.demo.jooq.db.tables.records.StoresRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Stores extends TableImpl<StoresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.stores</code>
     */
    public static final Stores STORES = new Stores();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoresRecord> getRecordType() {
        return StoresRecord.class;
    }

    /**
     * The column <code>public.stores.id</code>.
     */
    public final TableField<StoresRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.stores.address</code>.
     */
    public final TableField<StoresRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.stores.city</code>.
     */
    public final TableField<StoresRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.stores.country</code>.
     */
    public final TableField<StoresRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.stores.currency</code>.
     */
    public final TableField<StoresRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.stores.name</code>.
     */
    public final TableField<StoresRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Stores(Name alias, Table<StoresRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Stores(Name alias, Table<StoresRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.stores</code> table reference
     */
    public Stores(String alias) {
        this(DSL.name(alias), STORES);
    }

    /**
     * Create an aliased <code>public.stores</code> table reference
     */
    public Stores(Name alias) {
        this(alias, STORES);
    }

    /**
     * Create a <code>public.stores</code> table reference
     */
    public Stores() {
        this(DSL.name("stores"), null);
    }

    public <O extends Record> Stores(Table<O> path, ForeignKey<O, StoresRecord> childPath, InverseForeignKey<O, StoresRecord> parentPath) {
        super(path, childPath, parentPath, STORES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StoresPath extends Stores implements Path<StoresRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StoresPath(Table<O> path, ForeignKey<O, StoresRecord> childPath, InverseForeignKey<O, StoresRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StoresPath(Name alias, Table<StoresRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StoresPath as(String alias) {
            return new StoresPath(DSL.name(alias), this);
        }

        @Override
        public StoresPath as(Name alias) {
            return new StoresPath(alias, this);
        }

        @Override
        public StoresPath as(Table<?> alias) {
            return new StoresPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StoresRecord> getPrimaryKey() {
        return Keys.STORES_PKEY;
    }

    @Override
    public List<UniqueKey<StoresRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.STORES_NAME_KEY);
    }

    private transient StoreFruitPricesPath _storeFruitPrices;

    /**
     * Get the implicit to-many join path to the
     * <code>public.store_fruit_prices</code> table
     */
    public StoreFruitPricesPath storeFruitPrices() {
        if (_storeFruitPrices == null)
            _storeFruitPrices = new StoreFruitPricesPath(this, null, Keys.STORE_FRUIT_PRICES__STORE_ID_FK.getInverseKey());

        return _storeFruitPrices;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.fruits</code>
     * table
     */
    public FruitsPath fruits() {
        return storeFruitPrices().fruits();
    }

    @Override
    public Stores as(String alias) {
        return new Stores(DSL.name(alias), this);
    }

    @Override
    public Stores as(Name alias) {
        return new Stores(alias, this);
    }

    @Override
    public Stores as(Table<?> alias) {
        return new Stores(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stores rename(String name) {
        return new Stores(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stores rename(Name name) {
        return new Stores(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stores rename(Table<?> name) {
        return new Stores(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Condition condition) {
        return new Stores(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stores where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stores whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
