/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db.tables.records;


import ch.martinelli.demo.jooq.db.tables.Fruits;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FruitsRecord extends UpdatableRecordImpl<FruitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fruits.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fruits.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fruits.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fruits.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.fruits.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fruits.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FruitsRecord
     */
    public FruitsRecord() {
        super(Fruits.FRUITS);
    }

    /**
     * Create a detached, initialised FruitsRecord
     */
    public FruitsRecord(Long id, String description, String name) {
        super(Fruits.FRUITS);

        setId(id);
        setDescription(description);
        setName(name);
        resetChangedOnNotNull();
    }
}
