/*
 * This file is generated by jOOQ.
 */
package ch.martinelli.demo.jooq.db.tables.records;


import ch.martinelli.demo.jooq.db.tables.StoreFruitPrices;

import java.math.BigDecimal;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StoreFruitPricesRecord extends UpdatableRecordImpl<StoreFruitPricesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.store_fruit_prices.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.store_fruit_prices.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.store_fruit_prices.fruit_id</code>.
     */
    public void setFruitId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.store_fruit_prices.fruit_id</code>.
     */
    public Long getFruitId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.store_fruit_prices.store_id</code>.
     */
    public void setStoreId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.store_fruit_prices.store_id</code>.
     */
    public Long getStoreId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreFruitPricesRecord
     */
    public StoreFruitPricesRecord() {
        super(StoreFruitPrices.STORE_FRUIT_PRICES);
    }

    /**
     * Create a detached, initialised StoreFruitPricesRecord
     */
    public StoreFruitPricesRecord(BigDecimal price, Long fruitId, Long storeId) {
        super(StoreFruitPrices.STORE_FRUIT_PRICES);

        setPrice(price);
        setFruitId(fruitId);
        setStoreId(storeId);
        resetChangedOnNotNull();
    }
}
